apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: foodloop
  labels:
    app: ai-service
    app.kubernetes.io/part-of: foodloop
spec:
  type: ClusterIP
  selector:
    app: ai-service
  ports:
    - name: http
      port: 8002
      targetPort: http
