apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: foodloop
  labels:
    app: frontend
    app.kubernetes.io/part-of: foodloop
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
