apiVersion: v1
kind: Service
metadata:
  name: organization-service
  namespace: foodloop
  labels:
    app: organization-service
    app.kubernetes.io/part-of: foodloop
spec:
  type: ClusterIP
  selector:
    app: organization-service
  ports:
    - name: http
      port: 4003
      targetPort: http
